imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            handler:      nested
            action_level: %monolog_action_level%
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        url: "%database_url%"
        host:     "%database_host_prod%"
        port:     "%database_port_prod%"
        dbname:   "%database_name_prod%"
        user:     "%database_user_prod%"
        password: "%database_password_prod%"
        charset:  UTF8
        #   unix_socket: /tmp/mysql.sock
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
