# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
    your_service_name:
        class: AppBundle\Controller\CiqTController


    azine_email.example.web_view_service:
        class: Azine\EmailBundle\Services\AzineWebViewService
        arguments:
          $router:       "@router"



