# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    your_service_name:
        class: AppBundle\Controller\CiqTController


    # src/Your/AwesomeBundle/Resources/config/services.ym

    # the notifierservice is required, as you MUST provide your own implementation
    your.awesome.bundle.notifierservice:
        class: AppBundle\Services\ExampleNotifierService
        arguments:
          mailer:             "@azine_email_template_twig_swift_mailer"
          twig:               "@twig"
          logger:             "@logger"
          router:             "@router"
          entityManager:      "@doctrine.orm.entity_manager"
          templateProvider:   "@azine_email_template_provider"
          recipientProvider:  "@azine_email_recipient_provider"
          translatorService:  "@translator.default"
          parameters:
            newsletter_interval : "%azine_email_newsletter_interval%"
            newsletter_send_time: "%azine_email_newsletter_send_time%"
            templates_newsletter:     "%azine_email_templates_newsletter%"
            templates_notifications:  "%azine_email_templates_notifications%"
            templates_content_item:   "%azine_email_templates_content_item%"
            
    # if you don't add new templates, the template_provider is optional
    # this is just an example! Your implementation might need other parameters.
    your.awesome.bundle.template_provider:
        class: AppBundle\Services\ExampleTemplateProvider
        arguments:
          router:       "@router"
          translator:   "@translator.default"
          parameters:
            image_dir:  "%azine_email_image_dir%"
            allowed_images_folders: "%azine_email_allowed_images_folders%"
            tracking_params_campaign_name: "%azine_email_tracking_params_campaign_name%"
            tracking_params_campaign_term: "%azine_email_tracking_params_campaign_term%"
            tracking_params_campaign_content: "%azine_email_tracking_params_campaign_content%"
            tracking_params_campaign_medium: "%azine_email_tracking_params_campaign_medium%"
            tracking_params_campaign_source: "%azine_email_tracking_params_campaign_source%"

    ###################################################################
## Services you can use as default if you work with the FOSUserBundle
###################################################################
    azine_email.default.template_twig_swift_mailer:
        class: Azine\EmailBundle\Services\AzineTwigSwiftMailer
        arguments:
          $mailer:             "@mailer"
          $router:             "@router"
          $twig:               "@twig"
          $translator:         "@translator"
          $templateProvider:   "@azine_email_template_provider"
          $managerRegistry:    "@doctrine"
          $emailOpenTrackingCodeBuilder: "@azine_email_email_open_tracking_code_builder"
          $emailTwigExtension: "@azine.email.bundle.twig.filters"
          $parameters:
            template:
              confirmation :  "%fos_user.registration.confirmation.template%"
              resetting:      "%fos_user.resetting.email.template%"
              email_updating: "%fos_user.email_update_confirmation.template%"
            from_email:
              confirmation:   "%fos_user.registration.confirmation.from_email%"
              resetting:      "%fos_user.resetting.email.from_email%"
            no_reply:         "%azine_email_no_reply%"
          $immediateMailer:    "@swiftmailer.mailer.immediateMailer"

    azine_email.default.recipient_provider:
        class: Azine\EmailBundle\Services\AzineRecipientProvider
        arguments:
          $managerRegistry:    "@doctrine"
          $userClass:    "%azine_email_recipient_class%"
          $newsletterField:    "%azine_email_recipient_newsletter_field%"

    # if you don't add new templates and your newsletter does not need any dummy-data
    # then the web_view_service is optional
    # this is just an example! Your implementation might need other parameters.
    your.awesome.bundle.web_view_service:
        class: AppBundle\Services\ExampleWebViewService
        arguments:
          router:       "@router"

###################################################################
## Twig-Filter
###################################################################
    azine.email.bundle.twig.filters:
        class: Azine\EmailBundle\Services\AzineEmailTwigExtension
        public: false
        arguments:
          $templateProvider:   "@azine_email_template_provider"
          $translator:         "@translator"
          $domainsToTrack:     "%azine_email_domains_for_tracking%"
        tags:
            - { name: twig.extension }


